# raise_exception.py
def raise_exception():
    raise TypeError("This is a custom type exception.")
